package Vue;

public enum ETAT_IU {
    BIENVENUE, INSCRIPTION, INSCRIPTION_REUSSIE, PRE_CONNEXION , CONNEXION, RENDRE_DVD, VOIR_FILMS, ATTENTE_DVD,AJOUTER_AU_PANIER,CONFIRMER_AJOUTER_AU_PANIER, AUCUN
}
