package Vue;

public enum ETAT_IU {
    AFFICHER_PANIER,
    AJOUTER_AU_PANIER,
    AUCUN,
    BIENVENUE,
    CONFIRMER_AJOUTER_AU_PANIER,
    CONNEXION,
    INSCRIPTION,
    INSCRIPTION_REUSSIE,
    PARAMETRES_ABONNE,
    PARAMETRES_TECHNICIEN,
    PRE_CONNEXION ,
    RECHARGER,
    REGLER_PANIER_CB,
    RENDRE_DVD,
    VOIR_FILMS,
}
